"use strict";

// ===============================
// EDIT YOUR PERSONAL INFORMATION
// Replace the placeholder values when your public profiles are ready.
// ===============================
const portfolioData = {
  name: "Jamir Kurt Quillang",
  course: "BSIT – AIT",
  email: "jamirkurtquillang@gmail.com", // Replace this with your actual email address.
  github: "", // Add your full GitHub profile URL here.
  linkedin: "" // Add your full LinkedIn profile URL here.
};

// ===============================
// ADD NEW PROJECTS HERE
// Copy this structure, then add it to the projects array:
// { title: "", description: "", technologies: [], image: "assets/projects/project1.jpg", github: "", live: "", category: "Web" }
// Leave github or live blank to hide the related button. Do not add fake URLs.
// ===============================
const projects = [
  { title: "This Is For You Babeee", description: "A personal interactive web experience created to share a meaningful digital message.", technologies: ["HTML", "CSS", "JavaScript"], image: "assets/projects/this-is-for-you-babeee.svg", github: "", live: "https://thisisforyoubabeee.netlify.app/", category: "Web" },
  { title: "This Is For You Babee", description: "A creative browser-based experience that turns a personal idea into an engaging web page.", technologies: ["HTML", "CSS", "JavaScript"], image: "assets/projects/this-is-for-you-babee.svg", github: "", live: "https://thisisforyoubabee.netlify.app/", category: "JavaScript" },
  { title: "Happy My Wife Day", description: "A celebratory website designed as a thoughtful, interactive digital experience.", technologies: ["HTML", "CSS", "JavaScript"], image: "assets/projects/happy-my-wife-day.svg", github: "", live: "https://happymywifeday.netlify.app/", category: "Web" },
  { title: "Open Every 24 Hours", description: "A time-based web concept focused on creating a simple, memorable user experience.", technologies: ["HTML", "CSS", "JavaScript"], image: "assets/projects/open-every-24-hours.svg", github: "", live: "https://openevery24hrs.netlify.app/", category: "JavaScript" },
  { title: "Legal Companion", description: "A development demo for a legal companion dashboard and application concept.", technologies: ["PHP", "MySQL", "JavaScript"], image: "assets/projects/legal-companion.svg", github: "", live: "https://row-naturals-wages-reliable.trycloudflare.com/legal%20companion/dashboard.php", category: "Academic", developmentDemo: true }
];

const skillData = [
  ["Frontend", "HTML5", "https://cdn.simpleicons.org/html5/E34F26", "Familiar"], ["Frontend", "CSS3", "https://cdn.simpleicons.org/css/1572B6", "Learning"], ["Frontend", "JavaScript", "https://cdn.simpleicons.org/javascript/F7DF1E", "Developing"], ["Frontend", "Tailwind CSS", "https://cdn.simpleicons.org/tailwindcss/06B6D4", "Familiar"],
  ["Programming", "PHP", "https://cdn.simpleicons.org/php/777BB4", "Learning"], ["Programming", "Python", "https://cdn.simpleicons.org/python/3776AB", "Learning"], ["Programming", "C#", "https://cdn.simpleicons.org/csharp/512BD4", "Basic"], ["Database", "MySQL", "https://cdn.simpleicons.org/mysql/4479A1", "Familiar"],
  ["Tools", "Git", "https://cdn.simpleicons.org/git/F05032", "Learning"], ["Tools", "GitHub", "https://cdn.simpleicons.org/github/8B9AAF", "Familiar"], ["Tools", "VS Code", "https://cdn.simpleicons.org/visualstudiocode/007ACC", "Familiar"]
];
const learningData = [["⌘", "Web Development", "Creating responsive, accessible pages with modern frontend foundations.", "Current focus: HTML, CSS & JavaScript"], ["◫", "Backend Development", "Learning how server-side concepts support practical applications.", "Current focus: PHP fundamentals"], ["▦", "Database Development", "Exploring data organization, queries, and connected application concepts.", "Current focus: MySQL"], ["◌", "Artificial Intelligence", "Understanding the foundations behind intelligent systems.", "Current focus: AI fundamentals"], ["◉", "Chatbot Development", "Exploring conversational design and chatbot building blocks.", "Current focus: APIs & prompting"], ["↗", "Software Development", "Improving problem-solving through small projects and practice.", "Current focus: programming skills"]];

const $ = (selector, root = document) => root.querySelector(selector);
const create = (tag, className, text) => { const el = document.createElement(tag); if (className) el.className = className; if (text) el.textContent = text; return el; };

function externalLink(url, label, className = "button secondary") { if (!url) return null; const link = create("a", className, label); link.href = url; link.target = "_blank"; link.rel = "noopener noreferrer"; return link; }
function renderSkills() { const grid = $("#skills-grid"); skillData.forEach(([, name, logo, status]) => { const card = create("article", "skill-card reveal"); const image = document.createElement("img"); image.src = logo; image.alt = `${name} logo`; image.loading = "lazy"; image.onerror = () => { image.style.display = "none"; }; card.append(image, create("h3", "", name), create("p", "", status)); const level = create("div", "level"); level.setAttribute("aria-label", `Learning status: ${status}`); level.append(create("i")); card.append(level); grid.append(card); }); }
function renderLearning() { const grid = $("#learning-grid"); learningData.forEach(([icon, title, desc, focus]) => { const card = create("article", "learning-card reveal"); card.append(create("span", "learn-icon", icon), create("h3", "", title), create("p", "", desc), create("small", "", focus)); grid.append(card); }); }
function createProjectCard(project) { const card = create("article", "project-card reveal"); const visual = create("div", "project-image"), image = document.createElement("img"); if (project.image) { image.src = project.image; image.alt = `${project.title} preview`; image.loading = "lazy"; image.onerror = () => { image.remove(); }; visual.classList.add("has-image"); visual.append(image); } const content = create("div", "project-content"); const category = create("span", "project-category", project.category); content.append(category); if (project.developmentDemo) category.append(create("small", "demo-label", " DEVELOPMENT DEMO")); content.append(create("h3", "", project.title), create("p", "", project.description)); const tags = create("div", "tags"); project.technologies.forEach((tech) => tags.append(create("span", "", tech))); content.append(tags); const actions = create("div", "project-actions"), detail = create("button", "button primary", "View Details"); detail.type = "button"; detail.addEventListener("click", () => openModal(project)); actions.append(detail); const github = externalLink(project.github, "Source Code", "button secondary"); const live = externalLink(project.live, project.developmentDemo ? "Development Demo" : "View Project", "button secondary"); if (github) actions.append(github); if (live) actions.append(live); content.append(actions); card.append(visual, content); return card; }
function renderProjects(category = "All") { const grid = $("#projects-grid"); grid.replaceChildren(); const visible = category === "All" ? projects : projects.filter((project) => project.category === category); if (!visible.length) { grid.append(create("p", "empty-projects", "Projects are currently being built for this category.")); return; } visible.forEach((project) => grid.append(createProjectCard(project))); observeReveals(); }
function setupFilters() { const root = $("#project-filters"), categories = ["All", "Web", "JavaScript", "PHP", "AI", "Academic"]; categories.forEach((category) => { const button = create("button", category === "All" ? "active" : "", category); button.type = "button"; button.addEventListener("click", () => { root.querySelectorAll("button").forEach((btn) => btn.classList.remove("active")); button.classList.add("active"); renderProjects(category); }); root.append(button); }); }
function openModal(project) { const dialog = $("#project-modal"), root = $("#modal-content"); root.replaceChildren(); if (project.image) { const img = document.createElement("img"); img.className = "modal-image"; img.src = project.image; img.alt = `${project.title} preview`; root.append(img); } const content = create("div", "modal-content"); const title = create("h2", "", project.title); title.id = "modal-title"; const type = create("span", "project-category", project.category); if (project.developmentDemo) type.append(create("small", "demo-label", " DEVELOPMENT DEMO")); content.append(type, title, create("p", "", project.description)); const tags = create("div", "tags"); project.technologies.forEach((tech) => tags.append(create("span", "", tech))); content.append(tags); const actions = create("div", "project-actions"); const git = externalLink(project.github, "View Source Code", "button secondary"), live = externalLink(project.live, project.developmentDemo ? "Open Development Demo" : "Visit Project", "button primary"); if (git) actions.append(git); if (live) actions.append(live); if (actions.childNodes.length) content.append(actions); root.append(content); dialog.showModal(); $("#modal-close").focus(); }
function applyProfileLinks() { const setLink = (id, url) => { const el = $(id); if (!url) return; el.href = url; el.target = "_blank"; el.rel = "noopener noreferrer"; el.classList.remove("disabled-link"); el.removeAttribute("aria-disabled"); }; const email = portfolioData.email; $("#email-link").href = `mailto:${email}`; $("#footer-email").href = `mailto:${email}`; $("#email-text").textContent = email; setLink("#github-link", portfolioData.github); setLink("#footer-github", portfolioData.github); setLink("#github-cta", portfolioData.github); setLink("#linkedin-link", portfolioData.linkedin); setLink("#footer-linkedin", portfolioData.linkedin); }
function terminalAnimation() { const body = $("#terminal-body"), lines = [["jamir@portfolio:~$ whoami", "Jamir Kurt Quillang"], ["jamir@portfolio:~$ role", "BSIT – AIT Student"], ["jamir@portfolio:~$ focus", "Web Development + AI"], ["jamir@portfolio:~$ status", "Learning / Building / Improving"]]; let index = 0; const addLine = () => { if (index >= lines.length) { const cursor = create("span", "cursor"); cursor.setAttribute("aria-hidden", "true"); body.append(cursor); return; } const [command, answer] = lines[index++]; const c = create("div", "command", command), a = create("div", "terminal-answer", answer); body.append(c, a); setTimeout(addLine, 260); }; addLine(); }
function setupContactForm() { $("#contact-form").addEventListener("submit", (event) => { event.preventDefault(); const form = event.currentTarget, name = form.elements.name.value.trim(), email = form.elements.email.value.trim(), subject = form.elements.subject.value.trim(), message = form.elements.message.value.trim(), output = $("#form-message"); const emailValid = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email); output.className = "form-message"; if (!name || !emailValid || !message) { output.textContent = !name ? "Please enter your name." : !emailValid ? "Please enter a valid email address." : "Please enter a message."; return; } output.classList.add("success"); output.textContent = "Opening your email app…"; const mailSubject = encodeURIComponent(subject || `Portfolio message from ${name}`); const mailBody = encodeURIComponent(`Name: ${name}\nEmail: ${email}\n\n${message}`); window.location.href = `mailto:${portfolioData.email}?subject=${mailSubject}&body=${mailBody}`; }); }
function observeReveals() { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add("in-view"); observer.unobserve(entry.target); } }), { threshold: .12 }); document.querySelectorAll(".reveal:not(.in-view)").forEach((element) => observer.observe(element)); }
function initNavigation() { const header = $("#site-header"), menu = $("#menu-button"), links = $("#nav-links"), back = $("#back-to-top"); menu.addEventListener("click", () => { const open = links.classList.toggle("open"); menu.setAttribute("aria-expanded", String(open)); menu.setAttribute("aria-label", open ? "Close navigation menu" : "Open navigation menu"); }); links.querySelectorAll("a").forEach((link) => link.addEventListener("click", () => { links.classList.remove("open"); menu.setAttribute("aria-expanded", "false"); })); const navAnchors = [...document.querySelectorAll(".nav-links a")]; const onScroll = () => { header.classList.toggle("scrolled", window.scrollY > 10); back.classList.toggle("visible", window.scrollY > 450); let current = "home"; document.querySelectorAll("main section[id]").forEach((section) => { if (window.scrollY >= section.offsetTop - 130) current = section.id; }); navAnchors.forEach((a) => a.classList.toggle("active", a.getAttribute("href") === `#${current}`)); }; window.addEventListener("scroll", onScroll, { passive: true }); onScroll(); back.addEventListener("click", () => window.scrollTo({ top: 0, behavior: "smooth" })); }
function initTheme() { const button = $("#theme-toggle"), saved = localStorage.getItem("portfolio-theme"); if (saved) document.documentElement.dataset.theme = saved; button.addEventListener("click", () => { const next = document.documentElement.dataset.theme === "light" ? "dark" : "light"; document.documentElement.dataset.theme = next; localStorage.setItem("portfolio-theme", next); }); }
document.addEventListener("DOMContentLoaded", () => { renderSkills(); renderLearning(); setupFilters(); renderProjects(); applyProfileLinks(); terminalAnimation(); setupContactForm(); initNavigation(); initTheme(); observeReveals(); $("#current-year").textContent = new Date().getFullYear(); $("#modal-close").addEventListener("click", () => $("#project-modal").close()); $("#project-modal").addEventListener("click", (event) => { if (event.target === event.currentTarget) event.currentTarget.close(); }); window.setTimeout(() => $("#loader").classList.add("hidden"), 500); });
